questions = [
    questions = [
        {
            "question":"What is a pathogen?",
            "correctAnswer":"A micro-organism that causes disease",
            "answer0":"A vector",
            "answer1":"A micro-organism that fights disease",
            "answer2":"A communicable disease",
        },
        {
            "question":"What is not a pathogen?",
            "correctAnswer":"Vector",
            "answer0":"Bacteria",
            "answer1":"Virus",
            "answer2":"Protist",
        },
        {
            "question":"How do pathogens spread in animals or plants?",
            "correctAnswer":"Direct contact, water and air",
            "answer0":"Direct contact and water",
            "answer1":"Direct contact",
            "answer2":"Water and air",
        },
        {
            "question":"How do viruses make you feel ill?",
            "correctAnswer":"Reproduce inside cells causing cell damage",
            "answer0":"Reproduce inside cells and release toxins",
            "answer1":"Reproduce and release antitoxins",
            "answer2":"Reproduce outside cells and release toxins",
        },
        {
            "question":"How do bacteria make you feel ill?",
            "correctAnswer":"Produce toxins",
            "answer0":"Reproduce inside cells causing cell damage",
            "answer1":"Release antitoxins",
            "answer2":"Reproduce inside cells",
        },
        {
            "question":"What type of pathogen causes measles?",
            "correctAnswer":"Virus",
            "answer0":"Bacteria",
            "answer1":"Fungi",
            "answer2":"Protist",
        },
        {
            "question":"What type of pathogen causes HIV?",
            "correctAnswer":"Virus",
            "answer0":"Protist",
            "answer1":"Bacteria",
            "answer2":"Fungi",
        },
        {
            "question":"What type of pathogen causes Gonorrhoea",
            "correctAnswer":"Bacteria",
            "answer0":"Fungi",
            "answer1":"Virus",
            "answer2":"Protist",
        },
        {
            "question":"What type of pathogen causes malaria?",
            "correctAnswer":"Protist",
            "answer0":"Virus",
            "answer1":"Bacteria",
            "answer2":"Fungi",
        },
        {
            "question":"What type of pathogen causes rose black spot?",
            "correctAnswer":"Fungi",
            "answer0":"Bacteria",
            "answer1":"Protist",
            "answer2":"Virus",
        },
        {
            "question":"How can measles be prevented?",
            "correctAnswer":"Vaccination",
            "answer0":"Contraception",
            "answer1":"Cooking food thoroughly",
            "answer2":"Washing hands",
        },
        {
            "question":"How can HIV be prevented?",
            "correctAnswer":"Contraception",
            "answer0":"Cooking foods thoroughly",
            "answer1":"Washing hands",
            "answer2":"Vaccination",
        },
        {
            "question":"How can Salmonella be prevented?",
            "correctAnswer":"Cooking foods thoroughly",
            "answer0":"Vaccination",
            "answer1":"Contraception",
            "answer2":"Washing hands",
        },
        {
            "question":"What are the symptoms of Gonorrhoea?",
            "correctAnswer":"Pain when urinating and a yellow discharge",
            "answer0":"Pain when urinating and a headache",
            "answer1":"Pain when urinating and vomiting",
            "answer2":"Pain when urinating and a rash",
        },
        {
            "question":"What is the mosquito known as in the malarial protist life cycle?",
            "correctAnswer":"Vector",
            "answer0":"Protist",
            "answer1":"Virus",
            "answer2":"Fungus",
        },
        {
            "question":"What is phagocytosis?",
            "correctAnswer":"Engulfing pathogens",
            "answer0":"Forming white blood cells",
            "answer1":"Killing pathogens",
            "answer2":"Eating pathgens",
        },
        {
            "question":"Why do antibiotics not work for viral infections?",
            "correctAnswer":"Viruses live and reproduce inside cells",
            "answer0":"Viruses grow inside cells",
            "answer1":"Viruses damage cells",
            "answer2":"Antibiotics would damage the cell",
        },
        {
            "question":"What are antibiotics?",
            "correctAnswer":"Medicine to help cure bacterial disease",
            "answer0":"Medicine to help cure disease",
            "answer1":"Medicine to help cure viral disease",
            "answer2":"Medicine to help cure fungal disease",
        }
    ]
]