const supabaseUrl = 'https://hxfnilmbkorrzhhnohzp.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4Zm5pbG1ia29ycnpoaG5vaHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODc2MTEzNTcsImV4cCI6MjAwMzE4NzM1N30.1RD7ecSAK9RGQJdFKk7iOck2KA70xvygYYdjXmJfWcg'
const supabaseClient = supabase.createClient(supabaseUrl, supabaseKey)