questions = [
    {
        "question": "What is a variable?",
        "correctAnswer": "Named memory address that holds a value",
        "answer0": "A function in Python",
        "answer1": "A programming construct",
        "answer2": "A type of selection statement",
    },
    {
        "question": "How could you assign a variable?",
        "correctAnswer": "<code>variable = value</code>",
        "answer0": "<code>value = variable</code>",
        "answer1": "<code>'variable' = 'value'</code>",
        "answer2": "<code>'value' = 'variable'</code>",
    },
    {
        "question": "What is a constant?",
        "correctAnswer": "A variable that cannot be changed",
        "answer0": "A number",
        "answer1": "Something that is in upper case",
        "answer2": "A variable that can be changed",
    },
    {
        "question": "What function is used to display a value in Python?",
        "correctAnswer": "<code>print()</code>",
        "answer0": "<code>input()</code>",
        "answer1": "<code>display()</code>",
        "answer2": "<code>output()</code>",
    },
    {
        "question": "What function is used for the user to input a value?",
        "correctAnswer": "<code>input()</code>",
        "answer0": "<code>display()</code>",
        "answer1": "<code>output()</code>",
        "answer2": "<code>print()</code>",
    },
    {
        "question": "What is the arithmetic operator for MOD in Python?",
        "correctAnswer": "<code>%</code>",
        "answer0": "<code>/</code>",
        "answer1": "<code>MOD</code>",
        "answer2": "<code>$</code>",
    },
    {
        "question": "What does the boolean operator <code>==</code> mean in Python?",
        "correctAnswer": "Equal to",
        "answer0": "Larger than",
        "answer1": "True",
        "answer2": "Less than",
    },
    {
        "question": "What is the error in the following IF statement in Python:<br><code>if variable = True:</code>",
        "correctAnswer": "Syntax error: Should be <code>==</code>",
        "answer0": "Logical error: <code>variable</code> can never be True",
        "answer1": "Logical error: True is a bad variable name",
        "answer2": "Syntax error: True is not a valid value",
    },
    {
        "question": "What is an integer?",
        "correctAnswer": "Whole number",
        "answer0": "Multiple Characters",
        "answer1": "Decimal Number",
        "answer2": "A single character",
    },
    {
        "question": "What is a real number?",
        "correctAnswer": "Decimal number",
        "answer0": "Whole number",
        "answer1": "True / False",
        "answer2": "Multiple characters",
    },
    {
        "question": "What is a character?",
        "correctAnswer": "Single letter / symbol / digit",
        "answer0": "Whole number",
        "answer1": "String of letters",
        "answer2": "Decimal number",
    },
    {
        "question": "What is a string?",
        "correctAnswer": "Multiple characters",
        "answer0": "Single character",
        "answer1": "True / False",
        "answer2": "Decimal number",
    },
    {
        "question": "What is boolean?",
        "correctAnswer": "True / False",
        "answer0": "String of characters",
        "answer1": "Decimal number",
        "answer2": "A single character",
    },
    {
        "question": "What is an example of an integer?",
        "correctAnswer": "13",
        "answer0": "F",
        "answer1": "8.0",
        "answer2": "Hello World",
    },
    {
        "question": "What is an example of an integer?",
        "correctAnswer": "8",
        "answer0": "Revision",
        "answer1": "5.9",
        "answer2": "True",
    },
    {
        "question": "What is an example of a real number?",
        "correctAnswer": "5.0",
        "answer0": "Hello World",
        "answer1": "5",
        "answer2": "True",
    },
    {
        "question": "What is an example of a real number?",
        "correctAnswer": "1.3",
        "answer0": "13",
        "answer1": "H",
        "answer2": "False",
    },
    {
        "question": "What is an example of a character?",
        "correctAnswer": "R",
        "answer0": "50",
        "answer1": "Hello World",
        "answer2": "5.0",
    },
    {
        "question": "What is an example of a character?",
        "correctAnswer": "5",
        "answer0": "50",
        "answer1": "5.0",
        "answer2": "Five",
    },
    {
        "question": "What is an example of a string?",
        "correctAnswer": "Hello World",
        "answer0": "H",
        "answer1": "50",
        "answer2": "500",
    },
    {
        "question": "What is an example of a string?",
        "correctAnswer": "Revision",
        "answer0": "50",
        "answer1": "5.0",
        "answer2": "S",
    },
    {
        "question": "What is an example of boolean?",
        "correctAnswer": "True",
        "answer0": "T",
        "answer1": "100",
        "answer2": "F",
    },
    {
        "question": "What is an example of boolean?",
        "correctAnswer": "False",
        "answer0": "F",
        "answer1": "T",
        "answer2": "10",
    }
]